name: Get Pending Changes in Changelog
description: ''
inputs:
  changelog-path:
    description: ''
    required: false
  verbose:
    description: ''
    required: false
    type: boolean    
    default: false
outputs:
  changelog:
    description: ''
    value: ${{ steps.latest-changes.outputs.changelog }}

runs:
  using: 'composite'
  steps:
  - name: checkout pr source branch
    uses: actions/checkout@v4
    with:
      ref: ${{ github.event.pull_request.head.ref }}

  - name: extract pending changes
    id: latest-changes
    run: |
      npm install
      node ./src/index.js '${{ github.workspace }}/${{ inputs.changelog-path }}'
    shell: bash
    working-directory: "${{ github.action_path }}"

  - name: show pending changes
    run: |
      echo "${{ steps.latest-changes.outputs.changelog }}"
    shell: bash
    if: ${{ inputs.verbose == true }}