name: Get Pending Changes in Changelog
description: ''
inputs:
  changelog-file:
    description: ''
    required: false
    default: 'CHANGELOG.md'
  verbose:
    description: ''
    required: false
    default: false
outputs:
  changelog:
    description: ''

runs:
  using: 'composite'
  steps:
  - name: checkout pr source branch
    uses: actions/checkout@v4
    with:
      ref: ${{ github.event.pull_request.head.ref }}

  - name: extract pending changes
    run: |
      npm install
      # echo "changelog=$(node ./src/index.js '${{ github.workspace }}/${{ inputs.changelog-file }}')" >> $GITHUB_OUTPUT

      node ./src/index.js '${{ github.workspace }}/${{ inputs.changelog-file }}'

    shell: bash
    working-directory: "${{ github.action_path }}"