name: Test Generate

on:
  push:
    paths:
      - 'generate/'

jobs:
  generate-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - run: |
        npm install
        npm run-script test
      working-directory: 'generate'