name: Run Tests

on:
  pull_request:
    branches:
    - main
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Generate - Install dependencies
        run: npm install
        working-directory: generate/src
      - name: Generate - Run Jest tests
        run: npm test
        working-directory: generate/src

      - name: Latest Changes - Install dependencies
        run: npm install
        working-directory: latest-changes/src
      - name: Latest Changes - Run Jest tests
        run: npm test
        working-directory: latest-changes/src
